name: JMeter CI/CD

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-jmeter:
    runs-on: ubuntu-latest
    container:
      image: justb4/jmeter:5.6.3
      options: --user root

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: List repository files
        run: ls -l

      - name: Run JMeter Test
        run: |
          mkdir -p /tmp/results
          jmeter -n -t ./P01_HTTPBinAPI_PT_StreeTest.jmx \
                 -l /tmp/results/results.jtl \
                 -e -o /tmp/results/report

      - name: Upload Test Report
        uses: actions/upload-artifact@v3
        with:
          name: JMeter-Report
          path: /tmp/results/report
